"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";

type Blog = { id:number; title:string; excerpt:string; content:string; image_url:string; author:string; status:"draft"|"published"; created_at?:string; updated_at?:string };
const showDate = (value?:string, detailed=false) => value ? new Date(value).toLocaleString("en-IN", detailed ? {dateStyle:"medium",timeStyle:"short"} : {dateStyle:"medium"}) : "Not available";

export function BlogPreview({ id }: { id:string }) {
  const router = useRouter();
  const [blog,setBlog] = useState<Blog|null>(null);
  const [loading,setLoading] = useState(true);
  const [error,setError] = useState("");

  useEffect(()=>{ let active=true; fetch(`/api/blogs?id=${encodeURIComponent(id)}`,{cache:"no-store"}).then(async response=>{const payload=await response.json();if(!response.ok||!payload.success)throw new Error(payload.error||"Blog post not found.");if(active)setBlog(payload.data);}).catch(reason=>active&&setError(reason instanceof Error?reason.message:"Unable to load blog post.")).finally(()=>active&&setLoading(false));return()=>{active=false};},[id]);

  async function remove(){if(!blog||!window.confirm("Are you sure you want to delete this blog post? This action cannot be undone."))return;const response=await fetch(`/api/blogs?id=${blog.id}`,{method:"DELETE"});const payload=await response.json();if(!response.ok||!payload.success){window.alert(payload.error||"Unable to delete blog post.");return}router.push("/admin/blogs");router.refresh();}

  if(loading)return <main className="previewState">Loading blog preview...</main>;
  if(!blog)return <main className="previewState"><p>{error||"Blog post not found."}</p><Link href="/admin/blogs">Back to Blog Management</Link></main>;
  const image=blog.image_url.startsWith("/")?blog.image_url:`/${blog.image_url}`;

  return <main className="blogPreviewPage"><header><h1>Blog Post Preview</h1><div><Link className="accent" href={`/admin/blogs/${blog.id}/edit`}>Edit</Link><Link href="/admin/blogs">Back</Link></div></header><div className="previewGrid">
    <article className="previewCard mainPreview"><h2>{blog.title}</h2><div className="previewMeta"><span>By {blog.author}</span><span>{showDate(blog.created_at)}</span><i className={blog.status}>{blog.status}</i></div>{blog.image_url&&<img className="previewImage" src={image} alt={blog.title}/>} {blog.excerpt&&<div className="previewExcerpt">{blog.excerpt}</div>}<div className="previewContent" dangerouslySetInnerHTML={{__html:blog.content}}/></article>
    <aside><section className="previewCard"><h3>Actions</h3><div className="actionStack"><Link className="primary" href={`/admin/blogs/${blog.id}/edit`}>Edit Post</Link><div className={`statusBox ${blog.status}`}>{blog.status}</div><button onClick={()=>void remove()}>Delete Post</button></div></section><section className="previewCard"><h3>Post Details</h3><dl><div><dt>ID</dt><dd>{blog.id}</dd></div><div><dt>Author</dt><dd>{blog.author}</dd></div><div><dt>Status</dt><dd>{blog.status}</dd></div><div><dt>Created</dt><dd>{showDate(blog.created_at,true)}</dd></div><div><dt>Updated</dt><dd>{showDate(blog.updated_at||blog.created_at,true)}</dd></div></dl></section><section className="previewCard"><h3>Frontend Preview</h3><p>This is the admin preview. The public website layout may appear differently.</p><Link className="frontend" href={`/single-blog?id=${blog.id}`} target="_blank">View Frontend Blog</Link></section></aside>
  </div><style>{`
    .blogPreviewPage,.previewState{min-height:100vh;padding:48px max(20px,calc((100vw - 1180px)/2));background:#050505;color:#fff}.previewState{display:grid;place-content:center;text-align:center}.previewState a{color:#ef7430}.blogPreviewPage>header{display:flex;align-items:center;justify-content:space-between;gap:20px;margin-bottom:24px}.blogPreviewPage>header h1{margin:0;font-size:clamp(28px,4vw,40px)}.blogPreviewPage>header div{display:flex;gap:9px}.blogPreviewPage a,.actionStack button{display:inline-flex;min-height:40px;padding:0 17px;align-items:center;justify-content:center;border:1px solid #444;border-radius:6px;color:#ddd;font-size:12px;font-weight:900;text-decoration:none}.blogPreviewPage a.accent,.actionStack a.primary{border-color:#ef7430;background:#ef7430;color:#fff}.previewGrid{display:grid;grid-template-columns:minmax(0,1fr) 320px;gap:22px;align-items:start}.previewCard{border:1px solid #333;border-radius:12px;background:#1a1a1a}.mainPreview{padding:24px;overflow:hidden}.mainPreview h2{margin:0 0 10px;font-size:clamp(26px,4vw,38px)}.previewMeta{display:flex;align-items:center;flex-wrap:wrap;gap:14px;margin-bottom:18px;color:#aaa;font-size:13px}.previewMeta i,.statusBox{padding:6px 11px;border-radius:999px;font-style:normal;font-weight:900;text-transform:capitalize}.previewMeta i.published,.statusBox.published{border:1px solid #285b38;background:#183c24;color:#9ee2b7}.previewMeta i.draft,.statusBox.draft{border:1px solid #594b20;background:#38311b;color:#ffd682}.previewImage{display:block;width:100%;max-height:390px;margin-bottom:18px;border:1px solid #333;border-radius:10px;object-fit:cover}.previewExcerpt{margin-bottom:20px;padding:16px;border:1px solid rgba(239,116,48,.24);border-radius:10px;background:rgba(239,116,48,.08);color:#ddd;font-weight:650;line-height:1.7}.previewContent{color:#d7d7d7;font-size:15px;line-height:1.9}.previewContent :is(h1,h2,h3,h4,h5,h6){color:#fff}.previewContent img{max-width:100%;height:auto;border-radius:10px}.previewGrid>aside{display:grid;gap:16px}.previewGrid>aside section{padding:18px}.previewGrid>aside h3{margin:0 0 15px;font-size:16px}.actionStack{display:grid;gap:10px}.actionStack .statusBox{text-align:center}.actionStack button{background:transparent;border-color:#8d2822;color:#ff8b84;cursor:pointer}.previewGrid aside dl{margin:0}.previewGrid aside dl div{display:flex;justify-content:space-between;gap:15px;padding:11px 0;border-bottom:1px solid #303030}.previewGrid aside dl div:last-child{border:0}.previewGrid dt{color:#888;font-size:12px}.previewGrid dd{margin:0;max-width:65%;color:#eee;font-size:12px;text-align:right}.previewGrid aside p{color:#999;font-size:12px;line-height:1.6}.blogPreviewPage a.frontend{width:100%;border-color:#ef7430;color:#ef7430}@media(max-width:900px){.previewGrid{grid-template-columns:1fr}}@media(max-width:600px){.blogPreviewPage{padding:28px 14px 60px}.blogPreviewPage>header{align-items:flex-start;flex-direction:column}.mainPreview{padding:17px}}
  `}</style></main>;
}
